json.id item.id
json.title item.title
json.price item.price
json.description item.description
json.image_url item.image_url
json.brand item.brand
json.link item.link
json.created_at item.created_at
json.updated_at item.updated_at